name: Scheduled Workflow

on:
  schedule:
    # 매시간 1분(UTC)에 실행
    - cron:  '1 * * * *'

jobs:
  build:
    runs-on: weather-api-calling

    steps:
    - uses: actions/checkout@latest

    - name: Run a script
      run: echo "Running a scheduled job"
